services:
  redpanda:
    image: redpandadata/redpanda:v24.3.6
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - '1'
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - '0'
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - '19092:19092'
      - '19644:9644'
    volumes:
      - redpanda-data:/var/lib/redpanda/data

volumes:
  redpanda-data:
