FROM eclipse-temurin:21-jre
WORKDIR /app
COPY fund-console/target/fund-console-0.0.1-SNAPSHOT.jar app.jar
COPY models/bge-small-zh-v1.5 /app/models/bge-small-zh-v1.5
EXPOSE 18080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
