<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.practice.fundgateway</groupId>
        <artifactId>fund-gateway-ai-center</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>fund-application</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.practice.fundgateway</groupId>
            <artifactId>fund-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.practice.fundgateway</groupId>
            <artifactId>fund-knowledge</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.practice.fundgateway</groupId>
            <artifactId>fund-guardian</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.practice.fundgateway</groupId>
            <artifactId>fund-integration</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-deepseek</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
